name: Artifacts workflow
on:
    push:
        branches:
          - master
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: get the codes
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm install ci
            - name: lint codes
              run: npm run lint
            - name: run the test
              run: npm run test
    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: get the codes
              uses: actions/checkout@v4
            - name: Install dependecnies
              run: npm install ci
            - name: build the app
              run: npm run build      
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist-without-markdown
                path: |
                    dependency
                    
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                name: Archive production artifacts
            - name: listing the files
              run: ls
            - name: deploy the code
              run: echo "deploying the application..........."
                                      